services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: helloworld
    volumes:
      - db_data:/var/lib/mysql


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db


  keycloak-db:
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    volumes:
      - keycloak_data:/var/lib/postgresql/data


  configure-keycloak:
    build: ./keycloak
    depends_on:
      - keycloak

  backend:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=helloworld
    depends_on:
      - database
      - keycloak


volumes:
  db_data:
  keycloak_data:
