apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-and-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-docker-registry/backend-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: KEYCLOAK_URL
          value: "http://keycloak-service:8080"
        - name: KEYCLOAK_REALM
          valueFrom:
            secretKeyRef:
              name: keycloak-config
              key: realm
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: keycloak-config
              key: clientId
      - name: db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: mydatabase
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
