apiVersion: v1
kind: Service
metadata:
  name: backend-and-db-service
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
