apiVersion: apps/v1
kind: Deployment
metadata:
  name: configure-keycloak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configure-keycloak
  template:
    metadata:
      labels:
        app: configure-keycloak
    spec:
      containers:
      - name: configure-keycloak
        image: your-docker-registry/configure-keycloak:latest
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_URL
          value: "http://keycloak-service:8080"
