apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      initContainers:
      - name: init-postgresql
        image: busybox
        command: ['sh', '-c', 'rm -rf /var/lib/postgresql/data/pgdata/*; mkdir -p /var/lib/postgresql/data/pgdata']
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:12
        envFrom:
        - configMapRef:
            name: keycloak-db-config
        - secretRef:
            name: keycloak-db-secret
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -d
            - postgresql://$(DB_USER):$(DB_PASSWORD)@localhost:5432/$(DB_NAME)
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: keycloak-data
