apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 keycloak-db 5432; do echo "waiting for database"; sleep 5; done']
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.0
        envFrom:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: keycloak-secret
        ports:
        - containerPort: 8080
        command: ["kc.sh", "start"]
