name: Kubernetes Connection Debug

on:
  push:
    branches:
      - main
      - dev

jobs:
  debug-k8s-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Decode and Set Kubernetes context
        run: |
          echo "Decoding KUBE_CONFIG and setting up kubeconfig"
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          echo "Kubeconfig file content:"
          cat $HOME/.kube/config
          echo "Kubeconfig file created at $HOME/.kube/config"

      - name: Verify Kubernetes context
        run: |
          echo "Verifying kubeconfig context"
          kubectl config view

      - name: Check Kubernetes cluster connectivity
        run: |
          echo "Checking Kubernetes cluster connectivity"
          kubectl cluster-info
          kubectl get nodes
