name: 'CI - Code Coverage'

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./app
      - name: Run tests and check coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=app --cov-report=xml
        working-directory: ./app
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: app/coverage.xml
